openapi: 3.0.1
info:
  title: OpenAPI document
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Swagger UI
  - url: http://localhost:9090
    description: Post manager microservice

paths:
  /api/v1/posts:
    get:
      tags:
        - post-client
      operationId: getAllPosts
      responses:
        '200':
          content:
            application/json:
             schema:
                type: array
                items:
                  $ref: '#/components/schemas/PostResponseBody'
          description: posts returned successfully



components:
  schemas:
    PostResponseBody:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        content:
          type: string
        createdAt:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string