openapi: 3.0.1
info:
  title: OpenAPI document
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Swagger UI
  - url: http://localhost:9090
    description: Post manager microservice

paths:
  /api/v1/posts:
    post:
      tags:
        - post-client
      operationId: createPost
      requestBody:
        required: true
        content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostRequestBody'
      responses:
        '201':
          description: post created successfully

    get:
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 0
          required: true
          description: Page of post list
      tags:
        - post-client
      operationId: getAllPosts
      responses:
        '200':
          content:
            application/json:
             schema:
                type: array
                items:
                  $ref: '#/components/schemas/PostResponseBody'
          description: posts returned successfully



components:
  schemas:
    PostRequestBody:
      type: object
      required:
        - title
        - content
      properties:
        title:
          type: string
        content:
          type: string
        createdAt:
          type: string
    PostResponseBody:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        type:
          type: string
        content:
          type: string
        createdAt:
          type: string
        comments:
          type: array
          items:
            $ref: '#/components/schemas/CommentResponseBody'

    CommentResponseBody:
      type: object
      properties:
        id:
          type: string
        createdAt:
          type: string
        content:
          type: string
        like:
          type: boolean
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string